Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Assignment2.Models
{
    public class Trainer
    {


        public int TrainerId { get; set; }
        
        [Required(ErrorMessage = "First Name is required.")]
        [MinLength(2, ErrorMessage = "Should be more than 2 characters")]
        [MaxLength(15, ErrorMessage = "Should be less than 15 characters")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        
        [Required(ErrorMessage = "Last Name is required.")]
        [MinLength(2, ErrorMessage = "Should be more than 2 characters")]
        [MaxLength(15, ErrorMessage = "Should be less than 15 characters")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        
        public decimal Salary { get; set; }
        
        [Required]
        [Display(Name ="Date hired")]
        public DateTime DateHired { get; set; }
        
        [Display(Name ="Availability")]
        public bool IsAvailable { get; set; }

        //Navigation properties
        public virtual ICollection<Specialization> Specializations { get; set; }

    }
}

Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment2.DAL;
using Assignment2.Models;
using Assignment2.Models.ViewModels;
using Assignment2.Repositories;
using PagedList;

namespace Assignment2.Controllers
{
    public class TrainerController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private readonly TrainerRepo trainerRepo = new TrainerRepo();

        // GET: Trainer
        public ActionResult Index(string searchText, string selectOption, string sortOrder, int? pSize, int? page )
        {
            var trainers = trainerRepo.GetAll();
            #region Sorting

            ViewBag.ByLastName = String.IsNullOrEmpty(sortOrder) ? "LastNameDesc" : "";
            ViewBag.ByFirstName = sortOrder == "FirstNameAsc" ? "FirstNameDesc" : "FirstNameAsc";
            ViewBag.BySpecializationCount = sortOrder == "SpecializationAsc" ? "SpecializationDesc" : "SpecializationAsc";
            ViewBag.BySalary = sortOrder == "SalaryAsc" ? "SalaryAsc" : "SalaryDesc";
            ViewBag.ByDateHired = sortOrder == "DateHiredAsc" ? "DateHiredDesc" : "DateHiredAsc";
            ViewBag.ByAvailability = sortOrder == "Available" ? "Available" : "Unavailable";
            

            switch (sortOrder)
            {
                case "LastNameDesc": trainers = trainers.OrderByDescending(x => x.LastName).ToList(); break;

                case "FirstNameAsc": trainers = trainers.OrderBy(x => x.FirstName).ToList(); break;
                case "FirstNameDesc": trainers = trainers.OrderByDescending(x => x.FirstName).ToList(); break;

                case "SpecializationAsc": trainers = trainers.OrderBy(x => x.Specializations.Count).ToList(); break;
                case "SpecializationDesc": trainers = trainers.OrderByDescending(x => x.Specializations.Count).ToList(); break;

                case "DateHiredAsc": trainers = trainers.OrderBy(x => x.DateHired).ToList(); break;
                case "DateHiredDesc": trainers = trainers.OrderByDescending(x => x.DateHired).ToList(); break;
                
                case "SalaryAsc": trainers = trainers.OrderBy(x => x.Salary).ToList(); break;
                case "SalaryDesc": trainers = trainers.OrderByDescending(x => x.Salary).ToList(); break;
                    
                case "Available": trainers = trainers.OrderBy(x => x.IsAvailable).ToList(); break;
                case "Unavailable": trainers = trainers.OrderByDescending(x => x.IsAvailable).ToList(); break;

                default: trainers = trainers.OrderBy(x => x.LastName).ToList(); break;
            }
            #endregion

            #region Filtering
            if (!String.IsNullOrEmpty(searchText))
            {
                switch (selectOption)
                {
                    case "FirstName": trainers = trainers.Where(x => x.FirstName.ToUpper().Contains(searchText.ToUpper())).ToList(); break;
                    case "LastName": trainers = trainers.Where(x => x.LastName.ToUpper().Contains(searchText.ToUpper())).ToList(); break;
                    case "DateHired": trainers = trainers.Where(x => x.DateHired == DateTime.Parse(searchText)).ToList(); break;
                    case "Salary": trainers = trainers.Where(x => x.Salary == Decimal.Parse(searchText)).ToList(); break;
                    case "Specialization": trainers = trainers.Where(x => x.Specializations.Any(y => y.SpecializationType.Equals(searchText))).ToList(); break;
                    case "Availability": trainers = trainers.Where(x => x.IsAvailable == Boolean.Parse(searchText)).ToList(); break;
                }
            }
            #endregion

            int pageSize = pSize ?? 10;
            int pageNumber = page ?? 1;
            return View(trainers.ToPagedList(pageNumber,pageSize));
        }

        // GET: Trainer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = trainerRepo.FindById(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // GET: Trainer/Create
        public ActionResult Create()
        {
            TrainerCreateVM tc = new TrainerCreateVM();
            //ViewBag.TrainerSpecializations = new SelectList(db.Specializations.ToList(), "Specialization", "Specialization");
            //TrainerSpecializationViewBags();
            return View(tc);
        }

        // POST: Trainer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TrainerId,FirstName,LastName,Salary,DateHired,IsAvailable")] Trainer trainer, IEnumerable<int>SpecializationIds)
        {
            if (ModelState.IsValid)
            {
                trainerRepo.Create(trainer, SpecializationIds);
                return RedirectToAction("Index");
            }
            TrainerCreateVM tc = new TrainerCreateVM();
            //TrainerSpecializationViewBags();
            return View(tc);
        }

        // GET: Trainer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = trainerRepo.FindById(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            //TODO 5: Check viewmodel instances
            TrainerEditVM te = new TrainerEditVM(trainer);
            return View(te);
        }
        // POST: Trainer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TrainerId,FirstName,LastName,Salary,DateHired,IsAvailable")] Trainer trainer, IEnumerable<int> SpecializationIds)
        {
            //TODO 1: Highlight selected specializations.
            if (ModelState.IsValid)
            {
                trainerRepo.Edit(trainer, SpecializationIds);
                return RedirectToAction("Index");
            }
            trainerRepo.Attach(trainer);
            TrainerEditVM te = new TrainerEditVM(trainer);
            return View(te);
        }

        // GET: Trainer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = trainerRepo.FindById(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // POST: Trainer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            trainerRepo.Delete(id);
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            trainerRepo.Dispose();
        }

        public void TrainerSpecializationViewBags()
        {
            var specs = db.Specializations.ToList();

            ViewBag.TrainerSpecializations = new SelectList(specs, "Specialization", "Specialization");
        }
    }
}

Views/Trainer/Create.cshtml
@model Assignment2.Models.ViewModels.TrainerCreateVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Trainer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.FirstName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
            @Html.ValidationMessageFor(model => model.Trainer.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.LastName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
            @Html.ValidationMessageFor(model => model.Trainer.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.Salary, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
            @Html.ValidationMessageFor(model => model.Trainer.Salary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("SpecializationIds", "Specializations", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.SpecializationIds, null, htmlAttributes: new { @class = "form-control", size = "5" })
            @*  @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })*@
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.DateHired, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Trainer.DateHired, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", type="date"} })
            @Html.ValidationMessageFor(model => model.Trainer.DateHired, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Trainer.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Trainer.IsAvailable)
                @Html.ValidationMessageFor(model => model.Trainer.IsAvailable, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>



    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")



    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    @*<script type="text/javascript">

        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+0"
            });

        });
    </script>*@

}

Views/Trainer/Delete.cshtml
@model Assignment2.Models.Trainer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateHired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateHired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Trainer/Details.cshtml
@model Assignment2.Models.Trainer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Trainer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateHired)
        </dt>

        <dd>
            <text>@Model.DateHired.ToShortDateString()</text>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specializations)
        </dt>

        <dd>
            <ul>
                @foreach (var specialization in Model.Specializations)
                {
                    <li>@specialization.SpecializationType</li>
                }
            </ul>

        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TrainerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Trainer/Edit.cshtml
@model Assignment2.Models.ViewModels.TrainerEditVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Trainer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Trainer.TrainerId)

        <div class="form-group">
            @Html.LabelFor(model => model.Trainer.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trainer.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trainer.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trainer.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trainer.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trainer.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trainer.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trainer.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trainer.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("SpecializationIds", "Specializations", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(x=>x.SpecializationIds, null, htmlAttributes: new { @class = "form-control", size = "8" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trainer.DateHired, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trainer.DateHired, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Trainer.DateHired, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trainer.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Trainer.IsAvailable)
                    @Html.ValidationMessageFor(model => model.Trainer.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")



    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-10:+0"
            });

        });
    </script>
}

Views/Trainer/Index.cshtml
@model PagedList.IPagedList<Assignment2.Models.Trainer>


@using PagedList;
@using PagedList.Mvc;


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Trainer", FormMethod.Get))
{
    <div class="form-group">
        <label for="selectOption">Filtering Option:</label>
        <select id="selectOption" name="selectOption" class="form-control">
            <option value="FirstName">First Name</option>
            <option value="LastName">Last Name</option>
            <option value="DateHired">Date Hired</option>
            <option value="Salary">Salary</option>
            <option value="Specialization">Specialization</option>
            <option value="Availability">Availability</option>
        </select>

        @Html.Label("Search Text:")
        @Html.TextBox("searchText", null, new { id = "searchBox", type = "search", @class = "form-control", placeholder = "Search", autocomplete = "off" })


        <input id="searchButton" type="submit" value="Search for Trainer" class="btn btn-success" />
        <input id="resetButton" type="button" name="Clear Form" value="View All" class="btn btn-warning" />
    </div>


}

@*<div id="searchResults">
    <label for="result"><strong>Search results for</strong></label>
    <text id="result"></text>
</div>*@


<table class="table table-hover">
    <tr>
        <th>
            @Html.ActionLink("Last Name", "Index", "Trainer", new { sortOrder = ViewBag.ByLastName }, null)
        </th>
        <th>
            @Html.ActionLink("First Name", "Index", "Trainer", new { sortOrder = ViewBag.ByFirstName }, null)
        </th>
        <th>
            @Html.ActionLink("Salary", "Index", "Trainer", new { sortOrder = ViewBag.BySalary }, null)
        </th>
        <th>
            @Html.ActionLink("Date Hired", "Index", "Trainer", new { sortOrder = ViewBag.ByDateHired }, null)
        </th>
        <th>

            @Html.ActionLink("Specializations", "Index", "Trainer", new { sortOrder = ViewBag.BySpecializationCount }, null)
        </th>
        <th>
            @Html.ActionLink("Availability", "Index", "Trainer", new { sortOrder = ViewBag.ByAvailability }, null)
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var trainer in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => trainer.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => trainer.FirstName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => trainer.Salary)
            </td>
            <td>
                @trainer.DateHired.ToString("d")
            </td>
            <td>
                <ul>
                    @foreach (var spec in trainer.Specializations.OrderBy(x => x.SpecializationType))
                    {
                        <li>@spec.SpecializationType</li>
                    }
                </ul>

            </td>
            <td>
                @Html.DisplayFor(modelItem => trainer.IsAvailable)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = trainer.TrainerId }) |
                @Html.ActionLink("Details", "Details", new { id = trainer.TrainerId }) |
                @Html.ActionLink("Delete", "Delete", new { id = trainer.TrainerId })
            </td>
        </tr>
    }
</table>

Page @(Model.PageCount <Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, x => Url.Action("Index", "Trainer", new { page = x }))


@section ViewAllButtonJS{
    <script>
        $("#resetButton").click(function (e) {
            window.location.href='@Url.Action("Index", "Trainer")';
        });
    </script>
}

@section SearchInputChangeJS{
    <script>
        $("#selectOption").on('change', (function () {
            var option = $("#selectOption").val();
            var searchBox = $("#searchBox");
            if (option == 'DateHired') {
                searchBox.attr('type', 'date');
            }
            else if (option == 'Availability') {
                searchBox.replaceWith(
                    `
                                <label for="searchText">Availability</label>
                                <select id="searchText" name="searchText" class="form-control">
                                <option value="true">Yes</option>
                                <option value="false">No</option>
                            `);
            }
            else {
                searchBox.attr('type', 'search')
            }
        }));
    </script>
}

@section ResetSearchOnRefreshJS{
    <script>
        $(window).on('load', function () {
            $("#searchBox").val("");
        });
    </script>
}

@*@section GetSearchButtonData{
    <script>
        $("#searchButton").click(function () {
            var selectOption = $("#selectOption").val();
            var searchText = $("#searchBox").val();
            console.log(selectOption);
            console.log(searchText);
            $("#searchResults").html(
                `
                <label for="result"><strong>Search results for</strong></label>
                <text id="result"><strong>${selectOption}</strong><i>${searchText}</i></text>
                `
            );
        });
    </script>
    }*@